before_script:
  - "cp config/database.example.yml config/database.yml"
  - psql -c 'create database scripture_memory_api_test;' -U postgres
language: ruby
rvm:
  - 2.0.0-p0
script: "bundle exec rake db:migrate && bundle exec rspec spec"
