development:
  adapter: postgresql
  encoding: unicode
  database: scripture_memory_api_development
  pool: 5
  username: warren
  password:
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: scripture_memory_api_test
  pool: 5
  username: warren
  password:
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: scripture_memory_api_production
  pool: 5
  username: scripture_memory_api
  password:
